services:
  dns01-proxy:
    build:
      context: src/dns01-proxy
      dockerfile: Dockerfile
    image: harianto/dns01-proxy:latest

  # Optional Go image for rollback only.
  # acmedns-server:
  #   build:
  #     context: src/acmedns-server
  #     dockerfile: Dockerfile
  #   image: harianto/acmedns-server:latest
