services:
  acmedns-server:
    build:
      context: build/acmedns-server
      dockerfile: Dockerfile
    image: harianto/acmedns-server:latest

  acmedns-client:
    build:
      context: build/acmedns-client
      dockerfile: Dockerfile
    image: harianto/acmedns-client:latest

  acmedns-letsencrypt:
    build:
      context: build/acmedns-letsencrypt
      dockerfile: Dockerfile
    image: harianto/acmedns-letsencrypt:latest

