services:
  acmedns-nuxt:
    build:
      context: build/acmedns-nuxt
      dockerfile: Dockerfile
    image: harianto/acmedns-nuxt:latest

  # Optional Go image for rollback only.
  # acmedns-server:
  #   build:
  #     context: build/acmedns-server
  #     dockerfile: Dockerfile
  #   image: harianto/acmedns-server:latest
